<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="9" failed="1" ignored="2" total="15" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="iBridge" duration-ms="61923" started-at="2022-07-21T12:36:24Z" finished-at="2022-07-21T12:37:26Z">
    <groups>
    </groups>
    <test name="iBridge6" duration-ms="61923" started-at="2022-07-21T12:36:24Z" finished-at="2022-07-21T12:37:26Z">
      <class name="com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02">
        <test-method status="PASS" signature="setup(java.lang.String)[pri:0, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447]" name="setup" is-config="true" duration-ms="4322" started-at="2022-07-21T12:36:25Z" finished-at="2022-07-21T12:36:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="initiateCasesInBulkExtended()[pri:1, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447]" name="initiateCasesInBulkExtended" duration-ms="18293" started-at="2022-07-21T12:36:29Z" finished-at="2022-07-21T12:36:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initiateCasesInBulkExtended -->
        <test-method status="PASS" signature="dragDropBrowse()[pri:2, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447]" name="dragDropBrowse" duration-ms="16527" started-at="2022-07-21T12:36:47Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02.initiateCasesInBulkExtended" finished-at="2022-07-21T12:37:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dragDropBrowse -->
        <test-method status="PASS" signature="candidateEmailVerification()[pri:3, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447]" name="candidateEmailVerification" duration-ms="22444" started-at="2022-07-21T12:37:04Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02.dragDropBrowse" finished-at="2022-07-21T12:37:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- candidateEmailVerification -->
        <test-method status="FAIL" signature="candidateLoginBulkAccount()[pri:4, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447]" name="candidateLoginBulkAccount" duration-ms="51" started-at="2022-07-21T12:37:26Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02.candidateEmailVerification" finished-at="2022-07-21T12:37:26Z">
          <exception class="org.openqa.selenium.UnhandledAlertException">
            <message>
              <![CDATA[unexpected alert open: {Alert text : msg not found}
  (Session info: chrome=101.0.4951.54): msg not found
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'ARS-NBT-LAP-068', ip: '192.168.1.5', os.name: 'Linux', os.arch: 'amd64', os.version: '5.13.0-51-generic', java.version: '1.8.0_312'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 101.0.4951.54, chrome: {chromedriverVersion: 101.0.4951.41 (93c720db8323..., userDataDir: /tmp/.com.google.Chrome.3m1kbh}, goog:chromeOptions: {debuggerAddress: localhost:37221}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 8003335f4b416d988e29971ba3bc4c88]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.UnhandledAlertException: unexpected alert open: {Alert text : msg not found}
  (Session info: chrome=101.0.4951.54): msg not found
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'ARS-NBT-LAP-068', ip: '192.168.1.5', os.name: 'Linux', os.arch: 'amd64', os.version: '5.13.0-51-generic', java.version: '1.8.0_312'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 101.0.4951.54, chrome: {chromedriverVersion: 101.0.4951.41 (93c720db8323..., userDataDir: /tmp/.com.google.Chrome.3m1kbh}, goog:chromeOptions: {debuggerAddress: localhost:37221}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 8003335f4b416d988e29971ba3bc4c88
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:276)
at com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02.candidateLoginBulkAccount(TC_InitiateCasesInBulkExtended_02.java:130)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.UnhandledAlertException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- candidateLoginBulkAccount -->
        <test-method status="SKIP" signature="submittedForVerification()[pri:5, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447]" name="submittedForVerification" duration-ms="0" started-at="2022-07-21T12:37:26Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02.candidateLoginBulkAccount" finished-at="2022-07-21T12:37:26Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InitiateCasesInBulkExtended_02.submittedForVerification()[pri:5, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InitiateCasesInBulkExtended_02.submittedForVerification()[pri:5, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submittedForVerification -->
        <test-method status="SKIP" signature="submittedCasesTrackerWipCases()[pri:6, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447]" name="submittedCasesTrackerWipCases" duration-ms="0" started-at="2022-07-21T12:37:26Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02.submittedForVerification" finished-at="2022-07-21T12:37:26Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InitiateCasesInBulkExtended_02.submittedCasesTrackerWipCases()[pri:6, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InitiateCasesInBulkExtended_02.submittedCasesTrackerWipCases()[pri:6, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submittedCasesTrackerWipCases -->
        <test-method status="SKIP" signature="searchClientArsNoCaseList()[pri:7, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447]" name="searchClientArsNoCaseList" duration-ms="0" started-at="2022-07-21T12:37:26Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02.submittedCasesTrackerWipCases" finished-at="2022-07-21T12:37:26Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InitiateCasesInBulkExtended_02.searchClientArsNoCaseList()[pri:7, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InitiateCasesInBulkExtended_02.searchClientArsNoCaseList()[pri:7, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchClientArsNoCaseList -->
        <test-method status="SKIP" signature="verifyInsufficientDocsQcAllocator()[pri:8, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447]" name="verifyInsufficientDocsQcAllocator" duration-ms="0" started-at="2022-07-21T12:37:26Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02.searchClientArsNoCaseList" finished-at="2022-07-21T12:37:26Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InitiateCasesInBulkExtended_02.verifyInsufficientDocsQcAllocator()[pri:8, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InitiateCasesInBulkExtended_02.verifyInsufficientDocsQcAllocator()[pri:8, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInsufficientDocsQcAllocator -->
        <test-method status="SKIP" signature="verifyInsufficientDocsQuality()[pri:9, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447]" name="verifyInsufficientDocsQuality" duration-ms="0" started-at="2022-07-21T12:37:26Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02.verifyInsufficientDocsQcAllocator" finished-at="2022-07-21T12:37:26Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InitiateCasesInBulkExtended_02.verifyInsufficientDocsQuality()[pri:9, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InitiateCasesInBulkExtended_02.verifyInsufficientDocsQuality()[pri:9, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInsufficientDocsQuality -->
        <test-method status="SKIP" signature="verifyInsufficientAllocator()[pri:10, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447]" name="verifyInsufficientAllocator" duration-ms="0" started-at="2022-07-21T12:37:26Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02.verifyInsufficientDocsQuality" finished-at="2022-07-21T12:37:26Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InitiateCasesInBulkExtended_02.verifyInsufficientAllocator()[pri:10, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InitiateCasesInBulkExtended_02.verifyInsufficientAllocator()[pri:10, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInsufficientAllocator -->
        <test-method status="SKIP" signature="verifyInsufficientVerifier()[pri:11, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447]" name="verifyInsufficientVerifier" duration-ms="0" started-at="2022-07-21T12:37:26Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02.verifyInsufficientAllocator" finished-at="2022-07-21T12:37:26Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InitiateCasesInBulkExtended_02.verifyInsufficientVerifier()[pri:11, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InitiateCasesInBulkExtended_02.verifyInsufficientVerifier()[pri:11, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInsufficientVerifier -->
        <test-method status="SKIP" signature="verifyInsufficientpendingForFulfilment()[pri:12, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447]" name="verifyInsufficientpendingForFulfilment" duration-ms="0" started-at="2022-07-21T12:37:26Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02.verifyInsufficientVerifier" finished-at="2022-07-21T12:37:26Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InitiateCasesInBulkExtended_02.verifyInsufficientpendingForFulfilment()[pri:12, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InitiateCasesInBulkExtended_02.verifyInsufficientpendingForFulfilment()[pri:12, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInsufficientpendingForFulfilment -->
        <test-method status="SKIP" signature="verifyInsufficiencyFulfillment()[pri:13, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447]" name="verifyInsufficiencyFulfillment" duration-ms="0" started-at="2022-07-21T12:37:26Z" depends-on-methods="com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02.verifyInsufficientpendingForFulfilment" finished-at="2022-07-21T12:37:26Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_InitiateCasesInBulkExtended_02.verifyInsufficiencyFulfillment()[pri:13, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_InitiateCasesInBulkExtended_02.verifyInsufficiencyFulfillment()[pri:13, instance:com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02@3fb6a447] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInsufficiencyFulfillment -->
      </class> <!-- com.iBridge.testcases.TC_InitiateCasesInBulkExtended_02 -->
    </test> <!-- iBridge6 -->
  </suite> <!-- iBridge -->
</testng-results>
